services:
  envoy-kubewaf:
    image: ghcr.io/zazathomas/envoy-kubewaf:0.0.1
    container_name: envoy-kubewaf
    ports:
      - "9099:9099"
    environment:
      - LOG_LEVEL=INFO
      - ENABLE_GEOIP=true
      - GEOIP_DB_PATH=./geoip_db/GeoLite2-Country.mmdb
      - GEOIP_DEFAULT_BLOCK=true
      - WHITELISTED_COUNTRIES=IE,GB,NG
      - ENABLE_BOT_DETECTION=true
      - USER_BLACKLISTED_BOTS=Googlebot,Bingbot,Slurp
    volumes:
      - ./geoip_db:/geoip_db:ro
    restart: unless-stopped
    depends_on:
      geoip-updater:
        condition: service_healthy

  geoip-updater:
    image: curlimages/curl:8.1.0
    container_name: geoip-db-updater
    volumes:
      - ./geoip-data:/geoip_db
    env_file:
      - .env
    restart: always
    command: >
      /bin/sh -c "while true; do 
      echo \"$(date): Starting GeoIP DB Update...\"; 
      curl -f -L -u $${MAXMIND_ACCOUNT_ID}:$${MAXMIND_LICENSE_KEY} 'https://download.maxmind.com/geoip/databases/GeoLite2-Country/download?suffix=tar.gz' -o /tmp/db.tar.gz && 
      tar -xzf /tmp/db.tar.gz -C /geoip_db --strip-components=1 && 
      echo \"$(date): Update complete. Sleeping 24h...\"; 
      sleep 86400; 
      done"
    healthcheck:
      test: ["CMD", "test", "-f", "/geoip_db/GeoLite2-Country.mmdb"]
      interval: 5s
      timeout: 5s
      retries: 10